/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.Chucnang;
import client.G;

/**
 *
 * @author minhduc
 */
public class Nhomchuathamgia extends javax.swing.JPanel {
    public Nhomchuathamgia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dsnhomchuathamgia = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        dsnhomchuathamgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsnhomchuathamgiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dsnhomchuathamgia);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Danh sach nhom chua tham gia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dsnhomchuathamgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsnhomchuathamgiaMouseClicked
        // TODO add your handling code here:
        try {
            String value = Nhomchuathamgia.dsnhomchuathamgia.getSelectedValue();
            if(value!=null){
                Chucnang.Tatluong();
                int x=javax.swing.JOptionPane.showConfirmDialog(Index.nhomchuathamgiaPanel,"Tham gia nhom "+ value);
                if(x==javax.swing.JOptionPane.YES_OPTION){
                boolean thamgianhom = G.iControl.thamgianhom(G.tennguoidung,value);
                }
                Chucnang.Batluongnhomchuathamgia();
            }
        } catch (Exception e) {
            System.out.println("Loi tham gia nhom!");
        }
    }//GEN-LAST:event_dsnhomchuathamgiaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> dsnhomchuathamgia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
