/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.Chucnang;
import client.G;
import static gui.Index.guitinPanel;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import rmi.FileData;
import rmi.Tinnhan;

/**
 *
 * @author minhduc
 */
public class Tinnhannhom extends javax.swing.JPanel {

    public Tinnhannhom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        guitinnhom = new javax.swing.JButton();
        guitinnhomms = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tenfilenhomlabel = new javax.swing.JLabel();
        chonfilenhom = new javax.swing.JButton();
        guifilenhom = new javax.swing.JButton();
        guifilenhomms = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dstinnhannhom = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        noidungtinnhom = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Gui tin nhom");

        guitinnhom.setText("Gui tin");
        guitinnhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guitinnhomActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Gui file");

        chonfilenhom.setText("Chon file");
        chonfilenhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonfilenhomActionPerformed(evt);
            }
        });

        guifilenhom.setText("Gui file");
        guifilenhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guifilenhomActionPerformed(evt);
            }
        });

        dstinnhannhom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dstinnhannhomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dstinnhannhom);

        noidungtinnhom.setColumns(20);
        noidungtinnhom.setRows(5);
        jScrollPane2.setViewportView(noidungtinnhom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guitinnhomms, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(guitinnhom, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guifilenhom, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenfilenhomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chonfilenhom)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addComponent(guifilenhomms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guitinnhomms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tenfilenhomlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chonfilenhom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guifilenhomms, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guitinnhom)
                    .addComponent(guifilenhom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void guitinnhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guitinnhomActionPerformed
        try {
            // TODO add your handling code here:
            String noidung=this.noidungtinnhom.getText();
            Tinnhan tinnhan = new Tinnhan(G.tennguoidung,G.nhomdachon,noidung,"text");
            boolean guitinnhom = G.iControl.guitinnhom(tinnhan);
            if(guitinnhom==false){
                
                Tinnhannhom.guitinnhomms.setText("Gui tin that bai");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Tinnhannhom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guitinnhomActionPerformed

    private void chonfilenhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonfilenhomActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int x = fileChooser.showOpenDialog(this);
        if(x==javax.swing.JFileChooser.APPROVE_OPTION){
            G.file = fileChooser.getSelectedFile();
            Tinnhannhom.tenfilenhomlabel.setText(G.file.getName());
        }
    }//GEN-LAST:event_chonfilenhomActionPerformed

    private void guifilenhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guifilenhomActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
                String nguoinhan=G.nhomdachon;
                boolean guitenfile = G.iControl.guitinnhom(new Tinnhan(G.tennguoidung, nguoinhan, G.file.getName()+","+G.file.length()+"KB","file"));
                FileData fileData = new FileData(G.tennguoidung,nguoinhan,G.file.getName(),G.file.length());
                fileData.data = new byte[(int) G.file.length()];
                FileInputStream fileInputStream=new FileInputStream(G.file);
                int count;
                if((count = fileInputStream.read(fileData.data))>=0){
                    System.out.println("count(ReadFile) ="+count);
                }
                fileInputStream.close();
                boolean guifilenhom = G.iControl.guifilenhom(fileData);
                if(guitenfile==true&&guifilenhom==true){
                    System.out.println("Thanh cong");
                    Tinnhannhom.guifilenhomms.setText("da gui");
//                    Chucnang.HienthiDsTinnhannhom();
                }
        } catch (RemoteException ex) {
            Logger.getLogger(Tinnhannhom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Tinnhannhom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Tinnhannhom.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception e){
            System.out.println("loi gui file");
        }
    }//GEN-LAST:event_guifilenhomActionPerformed

    private void dstinnhannhomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dstinnhannhomMouseClicked
        // TODO add your handling code here:
        try {
            String value = Tinnhannhom.dstinnhannhom.getSelectedValue();
            if(value!=null){
                String[] data=value.split("\\|\\|");
                String[] fileinfo = data[3].split(",");
                if(data[1].equals("file")){
                    int x=javax.swing.JOptionPane.showConfirmDialog(guitinPanel, "Download "+fileinfo[0]);
                    if(x==javax.swing.JOptionPane.YES_OPTION){
                        FileOutputStream fileOutputStream;
                        File file = new File(fileinfo[0]);
                        fileOutputStream = new FileOutputStream(file);
                        FileData fileData = G.iControl.nhanfilenhom(data[2],G.nhomdachon, fileinfo[0]);
                        fileOutputStream.write(fileData.data);
                        fileOutputStream.close();
                    }

                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception e){
            System.out.println("Khong load duoc tin");
        }
    }//GEN-LAST:event_dstinnhannhomMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton chonfilenhom;
    public static javax.swing.JList<String> dstinnhannhom;
    public javax.swing.JButton guifilenhom;
    public static javax.swing.JLabel guifilenhomms;
    public javax.swing.JButton guitinnhom;
    public static javax.swing.JLabel guitinnhomms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea noidungtinnhom;
    public static javax.swing.JLabel tenfilenhomlabel;
    // End of variables declaration//GEN-END:variables
}
