/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.Chucnang;
import client.G;
import client.VoiceChat;
import static gui.Guitin.sendfilelabel;
import static gui.Guitin.sendlabel;
import static gui.Index.guitinPanel;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import rmi.FileData;
import rmi.Tinnhan;

/**
 *
 * @author minhduc
 */
public class Trochuyennguoidung extends javax.swing.JPanel {

    /**
     * Creates new form Trochuyennguoidung
     */
    public Trochuyennguoidung() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        noidung = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        sendfile = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dstinnhannguoidung = new javax.swing.JList<>();
        voicechat_off = new javax.swing.JButton();
        voicechat_on = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        noidung.setColumns(20);
        noidung.setRows(5);
        jScrollPane1.setViewportView(noidung);

        jButton1.setText("Gui tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gui file");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("chon file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        dstinnhannguoidung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dstinnhannguoidungMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dstinnhannguoidung);

        voicechat_off.setText("OFF");
        voicechat_off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voicechat_offActionPerformed(evt);
            }
        });

        voicechat_on.setText("ON");
        voicechat_on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voicechat_onActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Voice chat:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sendfile, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(29, 29, 29)
                            .addComponent(voicechat_on)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(voicechat_off))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendfile, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voicechat_off)
                    .addComponent(voicechat_on)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int x = fileChooser.showOpenDialog(this);
        if(x==javax.swing.JFileChooser.APPROVE_OPTION){
            G.file = fileChooser.getSelectedFile();
            Trochuyennguoidung.sendfile.setText(G.file.getName());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
                // TODO add your handling code here
                String noidung = Trochuyennguoidung.noidung.getText();
                String nguoinhan = G.nguoinhan;
                String nguoigui = G.tennguoidung;
                if(!nguoinhan.equals("")){
                    boolean guitin = G.iControl.guitin(new Tinnhan(nguoigui, nguoinhan, noidung,"text"));
                    if(guitin==true){
                         Trochuyennguoidung.noidung.setText("");
                    }
                }
                else{
                    sendlabel.setText("Chua co nguoi nhan");
                }
            } catch (RemoteException ex) {
            Logger.getLogger(Guitin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String nguoinhan=G.nguoinhan;
            if(!nguoinhan.equals("")){
                boolean guitenfile = G.iControl.guitin(new Tinnhan(G.tennguoidung, nguoinhan, G.file.getName()+","+G.file.length()+"KB","file"));
                FileData fileData = new FileData(G.tennguoidung, nguoinhan,G.file.getName(),G.file.length());
                fileData.data = new byte[(int) G.file.length()];
                FileInputStream fileInputStream=new FileInputStream(G.file);
                int count;
                if((count = fileInputStream.read(fileData.data))>=0){
                    System.out.println("count(ReadFile) ="+count);
                }
                fileInputStream.close();
                boolean guifile = G.iControl.guifile(fileData);
                if(guitenfile==true&&guifile==true){
                    Trochuyennguoidung.sendfile.setText("Da gui");
                }
            }
            else{
                sendfilelabel.setText("Chua co nguoi nhan");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(Guitin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Guitin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Guitin.class.getName()).log(Level.SEVERE, null, ex);
        }catch (Exception e){
            System.out.println("loi gui file");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dstinnhannguoidungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dstinnhannguoidungMouseClicked
        // TODO add your handling code here:
        try {
                if(G.dstindagui!=null){
                    String value = Trochuyennguoidung.dstinnhannguoidung.getSelectedValue();
                if(value!=null){ 
                    String[] data=value.split("\\|\\|");
                    String[] fileinfo = data[2].split(",");
                    if(data[1].equals("file")&& data[0].contains(">>")){
                        int x=javax.swing.JOptionPane.showConfirmDialog(guitinPanel, "Download "+fileinfo[0]);
                        if(x==javax.swing.JOptionPane.YES_OPTION){
                        FileOutputStream fileOutputStream;
                        File file = new File(fileinfo[0]);
                        fileOutputStream = new FileOutputStream(file);
                        FileData fileData = G.iControl.nhanfile(G.nguoinhan,G.tennguoidung, fileinfo[0]);
                        fileOutputStream.write(fileData.data);
                        fileOutputStream.close();
                        }
                    }
                }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            }catch (Exception e){
                System.out.println("Khong load duoc tin");
            }
    }//GEN-LAST:event_dstinnhannguoidungMouseClicked

    private void voicechat_onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voicechat_onActionPerformed
        Chucnang.BatVoiceChat();
    }//GEN-LAST:event_voicechat_onActionPerformed

    private void voicechat_offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voicechat_offActionPerformed
        Chucnang.TatVoicechat();
    }//GEN-LAST:event_voicechat_offActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JList<String> dstinnhannguoidung;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextArea noidung;
    public static javax.swing.JLabel sendfile;
    private javax.swing.JButton voicechat_off;
    private javax.swing.JButton voicechat_on;
    // End of variables declaration//GEN-END:variables
}
