/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clientv2.G;

/**
 *
 * @author minhduc
 */
public class Danhsachnhom extends javax.swing.JPanel {
    public Danhsachnhom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tatcanhomJlist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        tatcanhomJlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tatcanhomJlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tatcanhomJlist);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Danh sach tat ca nhom");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tatcanhomJlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tatcanhomJlistMouseClicked
        // TODO add your handling code here:
        try {
            String value= Danhsachnhom.tatcanhomJlist.getSelectedValue();
        int x=javax.swing.JOptionPane.showConfirmDialog(Index.danhsachnhomPanel,"Tham gia nhom "+ value);
        if(x==javax.swing.JOptionPane.YES_OPTION){
            boolean thamgianhom = G.iControl.thamgianhom(G.tennguoidung,value);
        }
        } catch (Exception e) {
            System.out.println("Loi tham gia nhom!");
        }
    }//GEN-LAST:event_tatcanhomJlistMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList<String> tatcanhomJlist;
    // End of variables declaration//GEN-END:variables
}
